## Basic Configuration
baseurl = "/"
languageCode = "en"

title = "Geries Simon"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
googleAnalytics = "UA-133653076-1"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Geries Simon"
    title = "Geries Simon"
    description = "A personal blog about my journey in life."
    authorimage = "/img/geries.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "Geries Simon."
    license = "CC BY-NC 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-nc/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    # github = "geriess"
    # instagram = "<username>"
    # xing = "<username>"
    linkedin = "geries"
    twitter = "geries"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"
    email = "simon@geries.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
#[[menu.main]]
#    name = "Portfolio"
#    identifier = "portfolio"
#    weight = 200
#    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
