baseurl = "https://geries.com"
languageCode = "en-us"
title = "Geries Simon's Blog"
author = "Geries Simon"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "aether"
description = "Personal Blog"
bgimg = "img/ignasi_pattern_s.png"
